# Generated by Django 2.1.4 on 2018-12-22 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ammout', models.PositiveIntegerField(default=1)),
                ('title', models.TextField(default=None, max_length=100)),
                ('img', models.ImageField(blank=True, default=None, upload_to='')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventarized_date', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('removed_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_added', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
