# Generated by Django 2.1.4 on 2018-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_adder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
