# Generated by Django 2.1.4 on 2018-12-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_adder', '0002_object_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='title',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
