# Generated by Django 2.1.4 on 2018-12-22 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_adder', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='object_adder.Category'),
        ),
    ]
