# Generated by Django 2.1.4 on 2018-12-23 12:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('object_adder', '0003_object_category'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
    ]
