# Generated by Django 2.1.4 on 2018-12-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_adder', '0004_auto_20181223_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object_adder.Category'),
        ),
    ]
